apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.7.6-standalone
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DESIGN
              valueFrom:
                configMapKeyRef:
                  name: adminer-configmap
                  key: adminer_design
            - name: ADMINER_DEFAULT_SERVER
              valueFrom:
                configMapKeyRef:
                  name: adminer-configmap
                  key: adminer_default_service
          resources:
            limits:
              memory: "750Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    app: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
